version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      # update libs
      - apt-get update
      #Headless Chrome
      - apt-get install libgbm1
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg --install google-chrome-stable_current_amd64.deb
      # - dpkg --install google-chrome*.deb

      # - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      # - apt-get install -y nodejs  #aws code build use ubuntu environement
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
      - npm install --save bootstrap@4
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build
      - npm run test:ci
  post_build:
    commands:
      - mv appspec.yml ./dist/angular-test-ci-cd-ec2
      - mv scripts ./dist/angular-test-ci-cd-ec2
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/angular-test-ci-cd-ec2